# Generated by Django 5.2 on 2025-04-07 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['order', 'title']},
        ),
        migrations.AddField(
            model_name='candidate',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='photo_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='position',
            name='position_type',
            field=models.CharField(choices=[('school_prefect', 'School Prefect'), ('protocol_prefect', 'Protocol Prefect'), ('sports_prefect', 'Sports Prefect'), ('entertainment_prefect', 'Entertainment Prefect'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.position'),
        ),
        migrations.AlterField(
            model_name='position',
            name='description',
            field=models.TextField(),
        ),
    ]
